# ------------------------------------------------Global Paths------------------------------------------------#
# Paths to various models
model2path:
  e5: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/LLMs/e5-base-v2/"
  bge: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/LLMs/bge-base-en-v1.5"
  contriever: ""
  llama2-7B-chat: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/LLMs/Llama-2-7b-chat-hf"
  llama2-7B: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/LLMs/Llama-2-7b-hf"
  llama2-13B: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/LLMs/Llama-2-13b-hf"
  llama2-13B-chat: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/LLMs/Llama-2-13b-chat-hf"
  
# Pooling methods for each embedding model
model2pooling:
  e5: "mean"
  bge: "cls"
  contriever: "mean"
  jina: 'mean'
  dpr: cls

# Indexes path for retrieval models
method2index:
  e5: /home/zangxiaoxue/sunzhongxiang/flashrag_data/retrieval-corpus/index/wiki18_100w_e5.index
  bm25: ~
  contriever: ~

# ------------------------------------------------Environment Settings------------------------------------------------#
# Directory paths for data and outputs
data_dir: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/retrieval-corpus/dataset/FlashRAG_datasets/"
save_dir: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/retrieval-corpus/output/"

gpu_id: "4,5,6,7"
dataset_name: "nq" # name of the dataset in data_dir
split: ["train","test",'dev']  # dataset split to load (e.g. train,dev,test)

# Sampling configurations for testing
test_sample_num: 10  # number of samples to test (only work in dev/test split), if None, test all samples
random_sample: False # whether to randomly sample the test samples

# Seed for reproducibility
seed: 2024

# Whether save intermediate data
save_intermediate_data: True
save_note: 'experiment'

# -------------------------------------------------Retrieval Settings------------------------------------------------#
# If set the name, the model path will be find in global paths
retrieval_method: "e5"  # name or path of the retrieval model. 
retrieval_model_path: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/LLMs/e5-base-v2/" # path to the retrieval model
index_path: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/retrieval-corpus/index/wiki18_100w_e5.index" # set automatically if not provided. 
faiss_gpu: False # whether use gpu to hold index
corpus_path: "/home/zangxiaoxue/sunzhongxiang/flashrag_data/retrieval-corpus/wiki18_100w.jsonl"  # path to corpus in '.jsonl' format that store the documents

instruction: ~ # instruction for the retrieval model
retrieval_topk: 1 # number of retrieved documents
retrieval_batch_size: 256  # batch size for retrieval
retrieval_use_fp16: True  # whether to use fp16 for retrieval model
retrieval_query_max_length: 128  # max length of the query
save_retrieval_cache: True # whether to save the retrieval cache
use_retrieval_cache: False # whether to use the retrieval cache
retrieval_cache_path: ~ # path to the retrieval cache
retrieval_pooling_method: ~ # set automatically if not provided
bm25_backend: bm25s # pyserini, bm25s
use_sentence_transformer: False

use_reranker: False # whether to use reranker
rerank_model_name: ~ # same as retrieval_method
rerank_model_path: ~ # path to reranker model, path will be automatically find in `model2path`
rerank_pooling_method: ~
rerank_topk: 5  # number of remain documents after reranking
rerank_max_length: 512 
rerank_batch_size: 256 # batch size for reranker
rerank_use_fp16: True

# -------------------------------------------------Generator Settings------------------------------------------------#
framework: openai # inference frame work of LLM, supporting: 'hf','vllm','fschat', 'openai'
generator_model: gpt-4o-mini # name or path of the generator model
# setting for openai model, only valid in openai framework
openai_setting:
  api_key: 
  base_url: https://api2.aigcbest.top/v1/
  timeout: 60

generator_model_path: ~
generator_max_input_len: 2048  # max length of the input
generator_batch_size: 4 # batch size for generation, invalid for vllm
generation_params:  
  max_tokens: 256
  temperature: 1.0
  #top_p: 1.0
use_fid: False # whether to use FID, only valid in encoder-decoder model
gpu_memory_utilization: 0.85 # ratio of gpu's memory usage for generator

use_fid: False # whether to use FID, only valid in encoder-decoder model

# -------------------------------------------------Refiner Settings------------------------------------------------#
# If set, the refiner will be used to refine the retrieval documents.
refiner_name: ~
refiner_model_path: ~

# Used for extractive method (e.g embedding models)
refiner_topk: 5 # number of remain sentence after refiner
refiner_pooling_method: 'mean' # pooling method of refiner model
refiner_encode_max_length: 256
# Used for abstractive method (e.g. generation models like bart-large-cnn)
refiner_max_input_length: 1024
refiner_max_output_length: 512

# Specify settings for llmlingua
llmlingua_config:
  rate: 0.55
  condition_in_question: 'after_condition'
  reorder_context: 'sort'
  dynamic_context_compression_ratio: 0.3
  condition_compare: True
  context_budget: "+100"
  rank_method: 'longllmlingua'
sc_config:
  'reduce_ratio': 0.5

# -------------------------------------------------Evaluation Settings------------------------------------------------#
# Metrics to evaluate the result
metrics: ['em','f1','acc','precision','recall','input_tokens'] 
# Specify setting for metric, will be called within certain metrics
metric_setting: 
  retrieval_recall_topk: 5
save_metric_score: True #　whether to save the metric score into txt file



